[master]
158.160.13.23 ansible_user=yc-user

[workers]
158.160.75.164 ansible_user=yc-user
158.160.3.101 ansible_user=yc-user
158.160.67.211 ansible_user=yc-user
158.160.11.233 ansible_user=yc-user

[all:children]
master
workers

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
