apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: multitool-tester
    image: wbitt/network-multitool:latest
    # Запускаем с bash для возможности выполнения команд
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]