apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  selector:
    app: nginx-multitool
  ports:
  - name: nginx-web
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  type: NodePort
