apiVersion: v1
kind: Pod
metadata:
  name: test-multitool-pod
  labels:
    app: test-multitool
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool:latest
    ports:
    - containerPort: 8080